version: '3.8'

services:
  aula:
    build: .
    container_name: aula-container
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/auladb2025
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: aula-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auladb2025
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
